Converted to babel
Had to disable code coverage reporting for now, not sure why but I'm
receiving the following error:

    /home/tim/git/diffhtml/node_modules/istanbul/lib/report/html.js:174
            structuredText[lineNumber].covered = count > 0 ? 'yes' : 'no';
                                                                     ^
    TypeError: Cannot set property 'covered' of undefined